Esercizio Tra i beginner datasets scaricabili all'indirizzo https://www.kaggle.com/datasets/ahmettezcantekin/beginner-datasets selezioniamo amazon.csv, un dataset contenente una serie di recensioni su Amazon. • Valutiamo la dimensione del dataset • Osserviamo quali sono i nomi di colonna • Visualizziamo dieci righe a caso; • Il dataset è bilanciato, ovvero: il numero di recensioni positive è uguale a quello delle negative, oppure no?

In [20]:
import pandas as pd

amazon_df = pd.read_csv("amazon.csv")

# Dimensione
print (amazon_df.shape)

# Colonne
print("Colonne:", amazon_df.columns)

print (amazon_df.index)

# 10 righe a caso
print (amazon_df.sample(10))

print (amazon_df)

(20000, 2)
Colonne: Index(['reviewText', 'Positive'], dtype='object')
RangeIndex(start=0, stop=20000, step=1)
                                              reviewText  Positive
14370  its realy hard to use on smaller pics. I would...         0
7794   Use this app everyday on my Kindle Fire and it...         1
12511  Really eases all file handling tasks.  Locatin...         1
14317  When all I had was a little iPod, they were on...         1
9794   its cool and funner than everyone says and I l...         1
8743   My nine month old daughter loves this app! She...         1
362    Very interesting and excellent app. Hope have ...         1
3614   When I saw the game, it just looked like a eas...         1
5330   I was looking for a different experience.  Thi...         0
287    I think everyone has played this by now.  Ad s...         1
                                              reviewText  Positive
0      This is a one of the best apps acording to a b...         1
1      This is a pretty good version of the game for ...         1
2      this is a really cool game. there are a bunch ...         1
3      This is a silly game and can be frustrating, b...         1
4      This is a terrific game on any pad. Hrs of fun...         1
...                                                  ...       ...
19995  this app is fricken stupid.it froze on the kin...         0
19996  Please add me!!!!! I need neighbors! Ginger101...         1
19997  love it!  this game. is awesome. wish it had m...         1
19998  I love love love this app on my side of fashio...         1
19999  This game is a rip off. Here is a list of thin...         0

[20000 rows x 2 columns]

In [22]:
print (amazon_df.describe())

           Positive
count  20000.000000
mean       0.761650
std        0.426085
min        0.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        1.000000

In [23]:
print (amazon_df["Positive"].value_counts())

Positive
1    15233
0     4767
Name: count, dtype: int64

Esercizio Il dataset diabetes.csv raccoglie persone con diabete o meno, e il valore di diverse variabili fisiologiche dei pazienti. • Osserviamone le dimensioni e un'anteprima di cinque righe; • Prendiamoci un po' di tempo per dare un'occhiata ai metadati delle colonne; • Stampiamo dei descrittori statistici del dataset; • Selezioniamo i dati relativi a diverse fasce di età: 20-29, 30-39, 40-50; • Qual è la media della pressione sanguigna diastolica per le diverse fasce di età?

In [43]:
import pandas as pd

diabetes_df = pd.read_csv("diabetes.csv")

# Dimensioni del dataset
print("Dimensioni:", diabetes_df.shape)

# Anteprima di 5 righe
print(diabetes_df.head(5))

fascia_20_29 = diabetes_df[(diabetes_df["Age (years)"] >= 20) & (diabetes_df["Age (years)"] <= 29)]

Dimensioni: (768, 9)
   Number of times pregnant  \
0                         6
1                         1
2                         8
3                         1
4                         0

   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                148
1                                                 85
2                                                183
3                                                 89
4                                                137

   Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                                72                                35
1                                66                                29
2                                64                                 0
3                                66                                23
4                                40                                35

   2-Hour serum insulin (mu U/ml)  \
0                               0
1                               0
2                               0
3                              94
4                             168

   Body mass index (weight in kg/(height in m)^2)  Diabetes pedigree function  \
0                                            33.6                       0.627
1                                            26.6                       0.351
2                                            23.3                       0.672
3                                            28.1                       0.167
4                                            43.1                       2.288

   Age (years)  Class variable
0           50               1
1           31               0
2           32               1
3           21               0
4           33               1

Metadati delle colonne

In [28]:
print(diabetes_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   Number of times pregnant                                                  768 non-null    int64
 1   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  768 non-null    int64
 2   Diastolic blood pressure (mm Hg)                                          768 non-null    int64
 3   Triceps skin fold thickness (mm)                                          768 non-null    int64
 4   2-Hour serum insulin (mu U/ml)                                            768 non-null    int64
 5   Body mass index (weight in kg/(height in m)^2)                            768 non-null    float64
 6   Diabetes pedigree function                                                768 non-null    float64
 7   Age (years)                                                               768 non-null    int64
 8   Class variable                                                            768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None

Descrittori statistici

In [29]:
print(diabetes_df.describe())

       Number of times pregnant  \
count                768.000000
mean                   3.845052
std                    3.369578
min                    0.000000
25%                    1.000000
50%                    3.000000
75%                    6.000000
max                   17.000000

       Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
count                                         768.000000
mean                                          120.894531
std                                            31.972618
min                                             0.000000
25%                                            99.000000
50%                                           117.000000
75%                                           140.250000
max                                           199.000000

       Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
count                        768.000000                        768.000000
mean                          69.105469                         20.536458
std                           19.355807                         15.952218
min                            0.000000                          0.000000
25%                           62.000000                          0.000000
50%                           72.000000                         23.000000
75%                           80.000000                         32.000000
max                          122.000000                         99.000000

       2-Hour serum insulin (mu U/ml)  \
count                      768.000000
mean                        79.799479
std                        115.244002
min                          0.000000
25%                          0.000000
50%                         30.500000
75%                        127.250000
max                        846.000000

       Body mass index (weight in kg/(height in m)^2)  \
count                                      768.000000
mean                                        31.992578
std                                          7.884160
min                                          0.000000
25%                                         27.300000
50%                                         32.000000
75%                                         36.600000
max                                         67.100000

       Diabetes pedigree function  Age (years)  Class variable
count                  768.000000   768.000000      768.000000
mean                     0.471876    33.240885        0.348958
std                      0.331329    11.760232        0.476951
min                      0.078000    21.000000        0.000000
25%                      0.243750    24.000000        0.000000
50%                      0.372500    29.000000        0.000000
75%                      0.626250    41.000000        1.000000
max                      2.420000    81.000000        1.000000

In [50]:
import pandas as pd

diabetes_df = pd.read_csv("diabetes.csv")

fascia_20_29 = diabetes_df[(diabetes_df["Age (years)"] >= 20) & (diabetes_df["Age (years)"] <= 29)] # selezione fascia di età 20-29
print(fascia_20_29)

fascia_30_39 = diabetes_df[(diabetes_df["Age (years)"] >= 30) & (diabetes_df["Age (years)"] <= 39)] # selezione fascia di età 30-39
print(fascia_20_29)

fascia_40_50 = diabetes_df[(diabetes_df["Age (years)"] >= 40) & (diabetes_df["Age (years)"] <= 50)] # selezione fascia di età 40-50
print(fascia_20_29) 

print("Media pressione 20-29:", fascia_20_29["Diastolic blood pressure (mm Hg)"].mean())
print("Media pressione 30-39:", fascia_30_39["Diastolic blood pressure (mm Hg)"].mean())
print("Media pressione 40-50:", fascia_40_50["Diastolic blood pressure (mm Hg)"].mean())

     Number of times pregnant  \
3                           1
6                           3
7                          10
20                          3
23                          9
..                        ...
753                         0
758                         1
760                         2
764                         2
767                         1

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
3                                                   89
6                                                   78
7                                                  115
20                                                 126
23                                                 119
..                                                 ...
753                                                181
758                                                106
760                                                 88
764                                                122
767                                                 93

     Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
3                                  66                                23
6                                  50                                32
7                                   0                                 0
20                                 88                                41
23                                 80                                35
..                                ...                               ...
753                                88                                44
758                                76                                 0
760                                58                                26
764                                70                                27
767                                70                                31

     2-Hour serum insulin (mu U/ml)  \
3                                94
6                                88
7                                 0
20                              235
23                                0
..                              ...
753                             510
758                               0
760                              16
764                               0
767                               0

     Body mass index (weight in kg/(height in m)^2)  \
3                                              28.1
6                                              31.0
7                                              35.3
20                                             39.3
23                                             29.0
..                                              ...
753                                            43.3
758                                            37.5
760                                            28.4
764                                            36.8
767                                            30.4

     Diabetes pedigree function  Age (years)  Class variable
3                         0.167           21               0
6                         0.248           26               1
7                         0.134           29               0
20                        0.704           27               0
23                        0.263           29               1
..                          ...          ...             ...
753                       0.222           26               1
758                       0.197           26               0
760                       0.766           22               0
764                       0.340           27               0
767                       0.315           23               0

[396 rows x 9 columns]
     Number of times pregnant  \
3                           1
6                           3
7                          10
20                          3
23                          9
..                        ...
753                         0
758                         1
760                         2
764                         2
767                         1

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
3                                                   89
6                                                   78
7                                                  115
20                                                 126
23                                                 119
..                                                 ...
753                                                181
758                                                106
760                                                 88
764                                                122
767                                                 93

     Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
3                                  66                                23
6                                  50                                32
7                                   0                                 0
20                                 88                                41
23                                 80                                35
..                                ...                               ...
753                                88                                44
758                                76                                 0
760                                58                                26
764                                70                                27
767                                70                                31

     2-Hour serum insulin (mu U/ml)  \
3                                94
6                                88
7                                 0
20                              235
23                                0
..                              ...
753                             510
758                               0
760                              16
764                               0
767                               0

     Body mass index (weight in kg/(height in m)^2)  \
3                                              28.1
6                                              31.0
7                                              35.3
20                                             39.3
23                                             29.0
..                                              ...
753                                            43.3
758                                            37.5
760                                            28.4
764                                            36.8
767                                            30.4

     Diabetes pedigree function  Age (years)  Class variable
3                         0.167           21               0
6                         0.248           26               1
7                         0.134           29               0
20                        0.704           27               0
23                        0.263           29               1
..                          ...          ...             ...
753                       0.222           26               1
758                       0.197           26               0
760                       0.766           22               0
764                       0.340           27               0
767                       0.315           23               0

[396 rows x 9 columns]
     Number of times pregnant  \
3                           1
6                           3
7                          10
20                          3
23                          9
..                        ...
753                         0
758                         1
760                         2
764                         2
767                         1

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
3                                                   89
6                                                   78
7                                                  115
20                                                 126
23                                                 119
..                                                 ...
753                                                181
758                                                106
760                                                 88
764                                                122
767                                                 93

     Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
3                                  66                                23
6                                  50                                32
7                                   0                                 0
20                                 88                                41
23                                 80                                35
..                                ...                               ...
753                                88                                44
758                                76                                 0
760                                58                                26
764                                70                                27
767                                70                                31

     2-Hour serum insulin (mu U/ml)  \
3                                94
6                                88
7                                 0
20                              235
23                                0
..                              ...
753                             510
758                               0
760                              16
764                               0
767                               0

     Body mass index (weight in kg/(height in m)^2)  \
3                                              28.1
6                                              31.0
7                                              35.3
20                                             39.3
23                                             29.0
..                                              ...
753                                            43.3
758                                            37.5
760                                            28.4
764                                            36.8
767                                            30.4

     Diabetes pedigree function  Age (years)  Class variable
3                         0.167           21               0
6                         0.248           26               1
7                         0.134           29               0
20                        0.704           27               0
23                        0.263           29               1
..                          ...          ...             ...
753                       0.222           26               1
758                       0.197           26               0
760                       0.766           22               0
764                       0.340           27               0
767                       0.315           23               0

[396 rows x 9 columns]
Media pressione 20-29: 65.34848484848484
Media pressione 30-39: 69.66666666666667
Media pressione 40-50: 74.21428571428571

Esercizio Il dataset insurance.csv contiene dati rispetto a caratteristiche e abitudini delle persone, e della zona in cui vivono, rispetto ai costi individuali per le cure mediche come premio per le assicurazioni sulla salute. • Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna; • Quali sono le medie di charges rispetto a region? Ci sono differenze significative? • E rispetto a smoker? E a sex? • Quali sono i descrittori statistici di bmi? Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi?

In [51]:
import pandas as pd

df = pd.read_csv("insurance.csv")

# Dimensioni
print("Dimensioni:", df.shape)

# Anteprima
print(df.head())

# Nomi colonne
print(df.columns.tolist())

Dimensioni: (1338, 7)
   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

In [52]:
#Medie di charges rispetto a region
df.groupby("region")["charges"].mean()

region
northeast    13406.384516
northwest    12417.575374
southeast    14735.411438
southwest    12346.937377
Name: charges, dtype: float64

Le regioni southeast e southwest tendono ad avere costi più alti, mentre northeast e northwest leggermente più bassi.

In [53]:
#Medie di charges rispetto a smoker

df.groupby("smoker")["charges"].mean()

smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64

smoker = yes → costi molto più alti

smoker = no → costi molto più bassi

In [54]:
#Medie di charges rispetto a sex

df.groupby("sex")["charges"].mean()

sex
female    12569.578844
male      13956.751178
Name: charges, dtype: float64

Differenze piccole: uomini e donne hanno costi simili.

In [55]:
#Descrittori statistici di bmi

df["bmi"].describe()

count    1338.000000
mean       30.663397
std         6.098187
min        15.960000
25%        26.296250
50%        30.400000
75%        34.693750
max        53.130000
Name: bmi, dtype: float64

In [56]:
#Quartili del BMI

quartili = df["bmi"].quantile([0.25, 0.50, 0.75])
print(quartili)

0.25    26.29625
0.50    30.40000
0.75    34.69375
Name: bmi, dtype: float64

In [57]:
#Minimo, media e massimo di charges per quartile di BMI
#Prima creiamo una colonna che assegna ogni persona al suo quartile:

df["bmi_quartile"] = pd.qcut(df["bmi"], 4, labels=["Q1", "Q2", "Q3", "Q4"])
#Poi calcoliamo i descrittori:
df.groupby("bmi_quartile")["charges"].agg(["min", "mean", "max"])

C:\Users\Giordana\AppData\Local\Temp\ipykernel_35376\1724200728.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("bmi_quartile")["charges"].agg(["min", "mean", "max"])

                    min          mean          max
bmi_quartile
Q1            1121.8739  10360.662825  38245.59327
Q2            1131.5066  11407.831468  62592.87309
Q3            1135.9407  14358.173081  60021.39897
Q4            1141.4451  16987.936691  63770.42801

In [58]:
df["bmi_quartile"] = pd.qcut(df["bmi"], 4, labels=["Q1", "Q2", "Q3", "Q4"])
df.groupby("bmi_quartile", observed=True)["charges"].agg(["min", "mean", "max"])

                    min          mean          max
bmi_quartile
Q1            1121.8739  10360.662825  38245.59327
Q2            1131.5066  11407.831468  62592.87309
Q3            1135.9407  14358.173081  60021.39897
Q4            1141.4451  16987.936691  63770.42801

Esercizio 1/2 Il dataset pokemon.csv contiene un database di Pokémon, con dati quali nome, tipi di attacco, valori di attacco/difesa/eccetera, e se sono o meno leggendari. • Verifichiamo la dimensione, un'anteprima e osserviamo i nomi di colonna; • È verosimile che la prima colonna dovrebbe essere un indice? • Confrontiamolo con l'indice messo automaticamente da Pandas: combaciano? • Se no, settare la prima colonna come indice.

In [60]:
import pandas as pd

df = pd.read_csv("pokemon.csv")

# Dimensioni
print("Dimensioni:", df.shape)

# Anteprima
print(df.head(15))

# Nomi colonne
print(df.columns.tolist())

Dimensioni: (800, 13)
     #                       Name Type 1  Type 2  Total  HP  Attack  Defense  \
0    1                  Bulbasaur  Grass  Poison    318  45      49       49
1    2                    Ivysaur  Grass  Poison    405  60      62       63
2    3                   Venusaur  Grass  Poison    525  80      82       83
3    3      VenusaurMega Venusaur  Grass  Poison    625  80     100      123
4    4                 Charmander   Fire     NaN    309  39      52       43
5    5                 Charmeleon   Fire     NaN    405  58      64       58
6    6                  Charizard   Fire  Flying    534  78      84       78
7    6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111
8    6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78
9    7                   Squirtle  Water     NaN    314  44      48       65
10   8                  Wartortle  Water     NaN    405  59      63       80
11   9                  Blastoise  Water     NaN    530  79      83      100
12   9    BlastoiseMega Blastoise  Water     NaN    630  79     103      120
13  10                   Caterpie    Bug     NaN    195  45      30       35
14  11                    Metapod    Bug     NaN    205  50      20       55

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
0        65       65     45           1      False
1        80       80     60           1      False
2       100      100     80           1      False
3       122      120     80           1      False
4        60       50     65           1      False
5        80       65     80           1      False
6       109       85    100           1      False
7       130       85    100           1      False
8       159      115    100           1      False
9        50       64     43           1      False
10       65       80     58           1      False
11       85      105     78           1      False
12      135      115     78           1      False
13       20       20     45           1      False
14       25       25     30           1      False
['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary']

La prima colonna dovrebbe essere un indice?
Nel dataset Pokémon classico (Kaggle), la prima colonna si chiama spesso:# - id - pokedex_number
E contiene valori come:1, 2, 3, 4, 5, ...
Quindi è verosimile che rappresenti l’indice naturale del dataset.

Per verificarlo, basta confrontare: l’indice automatico di Pandas → 0, 1, 2, 3 e la prima colonna → 1, 2, 3, 4, …

In [62]:
#Confronto tra indice Pandas e prima colonna

print(df.index[:10])          # indice Pandas
print(df.iloc[:10, 0])        # prima colonna

#se allora non combaciano:Pandas parte da 0 . Il dataset parte da 1. Questo è un segnale forte che la prima colonna è un vero indice.

RangeIndex(start=0, stop=10, step=1)
0    1
1    2
2    3
3    3
4    4
5    5
6    6
7    6
8    6
9    7
Name: #, dtype: int64

In [64]:
#Se NON combaciano → dobbiamo sistemare l’indice

df = pd.read_csv("pokemon.csv", index_col=0)

#Verifica finale

print(df.head())
print(df.index)

                    Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
#
1              Bulbasaur  Grass  Poison    318  45      49       49       65
2                Ivysaur  Grass  Poison    405  60      62       63       80
3               Venusaur  Grass  Poison    525  80      82       83      100
3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123      122
4             Charmander   Fire     NaN    309  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
#
1       65     45           1      False
2       80     60           1      False
3      100     80           1      False
3      120     80           1      False
4       50     65           1      False
Index([  1,   2,   3,   3,   4,   5,   6,   6,   6,   7,
       ...
       714, 715, 716, 717, 718, 719, 719, 720, 720, 721],
      dtype='int64', name='#', length=800)

 Esercizio 2/2 • Quali sono i Pokémon leggendari? • E quali sono i leggendari di tipo 1 Grass? • E leggendari di tipo 1 Ice o Fire? • Trasformiamo la colonna Name nell'indice; • Quali sono i Pokémon della prima generazione con attacco > 50 e HP < 60?

In [65]:
#Quali sono i Pokémon leggendari?
# la colonna si chiami Legendary (True/False):

legendary = df[df["Legendary"] == True]
print(legendary[["Name", "Type 1", "Type 2"]])

                    Name    Type 1    Type 2
#
144             Articuno       Ice    Flying
145               Zapdos  Electric    Flying
146              Moltres      Fire    Flying
150               Mewtwo   Psychic       NaN
150  MewtwoMega Mewtwo X   Psychic  Fighting
..                   ...       ...       ...
719              Diancie      Rock     Fairy
719  DiancieMega Diancie      Rock     Fairy
720  HoopaHoopa Confined   Psychic     Ghost
720   HoopaHoopa Unbound   Psychic      Dark
721            Volcanion      Fire     Water

[65 rows x 3 columns]

In [66]:
#Quali sono i leggendari di tipo 1 Grass?

legendary_grass = df[(df["Legendary"] == True) & (df["Type 1"] == "Grass")]
print(legendary_grass[["Name", "Type 1"]])

                  Name Type 1
#
492  ShayminLand Forme  Grass
492   ShayminSky Forme  Grass
640           Virizion  Grass

In [69]:
#Leggendari di tipo 1 Ice o Fire

legendary_ice_fire = df[
    (df["Legendary"] == True) &
    (df["Type 1"].isin(["Ice", "Fire"]))   #isin() controlla se ogni valore di una colonna appartiene a una lista (o set, o array).
                                           #Restituisce una Series booleana.
]
print(legendary_ice_fire[["Name", "Type 1"]])

          Name Type 1
#
144   Articuno    Ice
146    Moltres   Fire
244      Entei   Fire
250      Ho-oh   Fire
378     Regice    Ice
485    Heatran   Fire
721  Volcanion   Fire

In [72]:
#Trasformiamo la colonna Name nell’indice dopo aver caricato il dataset:

df = pd.read_csv("pokemon.csv", index_col=0)

df = df.set_index("Name")

print(df.index[:10])

Index(['Bulbasaur', 'Ivysaur', 'Venusaur', 'VenusaurMega Venusaur',
       'Charmander', 'Charmeleon', 'Charizard', 'CharizardMega Charizard X',
       'CharizardMega Charizard Y', 'Squirtle'],
      dtype='object', name='Name')

In [73]:
#Pokémon della prima generazione con:attack > 50 HP < 60
#Assumendo che la colonna della generazione si chiami Generation:

filtered = df[
    (df["Generation"] == 1) &
    (df["Attack"] > 50) &
    (df["HP"] < 60)
]

print(filtered[["Generation", "Attack", "HP"]])

            Generation  Attack  HP
Name
Charmander           1      52  39
Charmeleon           1      64  58
Wartortle            1      63  59
Rattata              1      56  30
Raticate             1      81  55
Spearow              1      60  40
Ekans                1      60  35
Pikachu              1      55  35
Sandshrew            1      75  50
Nidoran♂             1      57  46
Paras                1      70  35
Diglett              1      55  10
Dugtrio              1      80  35
Psyduck              1      52  50
Mankey               1      80  40
Growlithe            1      70  55
Bellsprout           1      75  50
Geodude              1      80  40
Graveler             1      95  55
Ponyta               1      85  50
Magneton             1      60  50
Farfetch'd           1      65  52
Doduo                1      85  35
Shellder             1      65  30
Cloyster             1      95  50
Krabby               1     105  30
Kingler              1     130  55
Hitmonlee            1     120  50
Hitmonchan           1     105  50
Koffing              1      65  40
Seadra               1      65  55
Goldeen              1      67  45
Eevee                1      55  55
Kabuto               1      80  30
Dratini              1      64  41

Interpretazione tipica (dataset standard Pokémon)
I leggendari sono ~70 Pokémon (Mewtwo, Lugia, Rayquaza, ecc.).

I leggendari Grass sono pochissimi (es. Shaymin).

I leggendari Ice/Fire includono Articuno, Moltres, Reshiram, Kyurem, ecc.

Impostare Name come indice è molto utile per ricerche e slicing.

I Pokémon di Gen 1 con Attack > 50 e HP < 60 includono vari Pokémon di tipo Bug, Poison, Normal.

Esercizio 1/2 Dai dataset in piattaforma, carichiamo il file con i dati dei pub, circoli e locali in Italia, chiamato Mappa-dei-pub-circoli-locali-in-Italia.csv Nota: il dataset non ha un encoding UTF-8 ma Latin1; inoltre il separatore non è una virgola, ma un punto e virgola. Dunque per leggerlo dovremo aggiungere i parametri encoding= e sep=, ad esempio: pd.read_csv(file_path, encoding="latin1", sep=";") dove file_path è la posizione del file nel nostro calcolatore.Esercizio 2/2 Esaminiamo il dataset: • quanti dati ci sono in totale? • quali sono i metadati? • stampiamo il primo elemento • stampiamo l'ultimo elemento • riusciamo a stampare un elemento a caso? • quali sono gli anni di inserimento presenti? • quante enoteche ci sono, e come si chiamano? L’ultimo punto potrebbe richiedere molti passaggi, perché i dati in questo dataset non hanno subìto un processo di pulizia e trasformazione adeguato!

In [82]:
#Caricamento del dataset.Il file:non è UTF‑8 → serve encoding="latin1", non usa la virgola → serve sep=";"

df = pd.read_csv(
    "Mappa-dei-pub-circoli-locali-in-Italia.csv",
    encoding="latin1",
    sep=";"
)

In [84]:
#analisi del dataset 1) Quanti dati ci sono in totale?

print("Dimensioni del dataset:", df.shape)

#Restituisce (righe, colonne).

#2) Quali sono i metadati?

print("Metadati del dataset:")
print(df.info())

#3) Stampiamo il primo elemento

print("Primo elemento:")
print(df.head(1))

#4) Stampiamo l’ultimo elemento

print("Ultimo elemento:")
print(df.tail(1))

#5) Stampiamo un elemento a caso

print("Elemento casuale:")
print(df.sample(5))

Dimensioni del dataset: (2635, 9)
Metadati del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2635 entries, 0 to 2634
Data columns (total 9 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Comune                           2635 non-null   object
 1   Provincia                        2635 non-null   object
 2   Regione                          2635 non-null   object
 3   Nome                             2337 non-null   object
 4   Anno inserimento                 2635 non-null   int64
 5   Data e ora inserimento           2635 non-null   object
 6   Identificatore in OpenStreetMap  2635 non-null   int64
 7   Longitudine                      2635 non-null   float64
 8   Latitudine                       2635 non-null   float64
dtypes: float64(2), int64(2), object(5)
memory usage: 185.4+ KB
None
Primo elemento:
  Comune Provincia Regione Nome  Anno inserimento Data e ora inserimento  \
0  ALTRO     ALTRO   ALTRO  NaN              2011   2011-06-25T23:17:43Z

   Identificatore in OpenStreetMap  Longitudine  Latitudine
0                       1339088150    13.733257    45.57583
Ultimo elemento:
     Comune              Provincia Regione          Nome  Anno inserimento  \
2634  TRANI  BARLETTA-ANDRIA-TRANI  Puglia  Well's Fargo              2009

     Data e ora inserimento  Identificatore in OpenStreetMap  Longitudine  \
2634   2009-08-10T12:44:03Z                        387223648    16.436765

      Latitudine
2634   41.267264
Elemento casuale:
       Comune                       Provincia         Regione  \
1530   FORLI'                          FORLI'  Emilia-Romagna
2401  NISCEMI                   CALTANISSETTA         Sicilia
205    GENOVA  CITTA' METROPOLITANA DI GENOVA         Liguria
2068   FORMIA                          LATINA           Lazio
2105   NAPOLI  CITTA' METROPOLITANA DI NAPOLI        Campania

                      Nome  Anno inserimento Data e ora inserimento  \
1530             The Abbey              2013   2013-12-22T10:19:17Z
2401              Pub Kaos              2013   2013-03-10T11:59:38Z
205   American Bar Cubilla              2011   2011-12-24T10:08:41Z
2068      Birreria Morgana              2013   2013-06-03T13:17:28Z
2105        Borgo Vittoria              2015   2015-04-28T16:46:40Z

      Identificatore in OpenStreetMap  Longitudine  Latitudine
1530                        972616878    12.040157   44.223043
2401                       2194128182    14.382681   37.145666
205                        1560393331     9.031044   44.383584
2068                       2330582936    13.612344   41.258185
2105                       3465921717    14.242642   40.832077

In [86]:
#6) Quali sono gli anni di inserimento presenti?
#Prima troviamo la colonna giusta (il dataset è sporco):

print("Nomi colonne:")
print(df.columns.tolist())
#Poi cerchiamo tutte le colonne che contengono “anno”:

print("Colonne che contengono 'anno':")
print([col for col in df.columns if "anno" in col.lower()])
#Supponiamo che la colonna corretta sia "Anno inserimento"

print("Anni di inserimento presenti:")
print(df["Anno inserimento"].unique())

Nomi colonne:
['Comune', 'Provincia', 'Regione', 'Nome', 'Anno inserimento', 'Data e ora inserimento', 'Identificatore in OpenStreetMap', 'Longitudine', 'Latitudine']
Colonne che contengono 'anno':
['Anno inserimento']
Anni di inserimento presenti:
[2011 2015 2010 2012 2014 2016 2013 2008 2009 2007]

In [96]:
#Normalizziamo la colonna Nome

df["nome_norm"] = df["Nome"].str.lower().str.strip()

print("\nEsempi di nome normalizzato:")
print(df["nome_norm"].head())

Esempi di nome normalizzato:
0                NaN
1        lenny's pub
2    murrayfield pub
3             snop?e
4                NaN
Name: nome_norm, dtype: object

In [97]:
#Filtriamo tutte le enoteche

enoteche = df[df["nome_norm"].str.contains("enoteca", na=False)]

print("\nPrime enoteche trovate:")
print(enoteche.head())

Prime enoteche trovate:
       Comune                       Provincia         Regione  \
64     TORINO  CITTA' METROPOLITANA DI TORINO        Piemonte
496    MILANO  CITTA' METROPOLITANA DI MILANO       Lombardia
1003     MALO                         VICENZA          Veneto
1491  FERRARA                         FERRARA  Emilia-Romagna
1492  FERRARA                         FERRARA  Emilia-Romagna

                               Nome  Anno inserimento Data e ora inserimento  \
64    Enoteca con Cucina""Tirolin""              2012   2012-01-24T14:30:04Z
496               Concordia Enoteca              2014   2014-04-01T11:15:38Z
1003                Enoteca Umberto              2013   2013-04-15T08:41:22Z
1491        Enoteca ""Al Brindisi""              2015   2015-03-31T17:33:38Z
1492         Enoteca ""da Massimo""              2015   2015-03-31T17:33:38Z

      Identificatore in OpenStreetMap  Longitudine  Latitudine  \
64                         1603586163     7.713993   45.065174
496                        2758108717     9.171033   45.450819
1003                       1659350138    11.418507   45.653453
1491                       1249699754    11.620326   44.835890
1492                       1249701207    11.619559   44.834824

                          nome_norm
64    enoteca con cucina""tirolin""
496               concordia enoteca
1003                enoteca umberto
1491        enoteca ""al brindisi""
1492         enoteca ""da massimo""

In [98]:
#Quante sono?

print("\nNumero totale di enoteche trovate:")
print(len(enoteche))

Numero totale di enoteche trovate:
6

In [99]:
#Come si chiamano?

print("\nNomi delle enoteche:")
print(enoteche["Nome"].unique())

Nomi delle enoteche:
['Enoteca con Cucina""Tirolin""' 'Concordia Enoteca' 'Enoteca Umberto'
 'Enoteca ""Al Brindisi""' 'Enoteca ""da Massimo""'
 'Enoteca Il Violino Rosso']